<?xml version="1.0" encoding="UTF-8"?>
<!--
  The approved browser presentation for the yellow3 Insights feed, v1.0.

  GENERATED by research/gen_feed_xsl.py. Do not hand-edit: the stylesheet below
  is the approved package stylesheet, and a hand edit here is a change to an
  approved design that nothing would catch.

  This file only ever DECORATES /feed.xml. The feed is the canonical, valid RSS
  2.0 document at that address; feed readers never see any of this.

  THE TOP MENU AND FOOTER ON THIS PAGE ARE A RATIFIED v1.1 OVERRIDE. v1.0 gave
  this presentation no menu, no footer and no logo; GPT superseded that for the
  feed view on 23 August 2026, keeping the shell's own tokens and the feed
  presentation scoped beneath .fv1. See research/approved/insights-subscribe-v1.1.md.
-->
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:atom="http://www.w3.org/2005/Atom"
                xmlns:media="http://search.yahoo.com/mrss/">
<xsl:output method="html" encoding="UTF-8" indent="yes"
            doctype-system="about:legacy-compat"/>

<!-- The publication date, spelled out. An item with no pubDate renders no date
     line at all, rather than an invented one. -->
<xsl:template name="pubdate">
  <xsl:param name="raw"/>
  <xsl:variable name="rest" select="normalize-space(substring-after($raw, ','))"/>
  <xsl:variable name="d" select="substring-before($rest, ' ')"/>
  <xsl:variable name="after" select="substring-after($rest, ' ')"/>
  <xsl:variable name="m" select="substring-before($after, ' ')"/>
  <xsl:variable name="y" select="substring-before(substring-after($after, ' '), ' ')"/>
  <xsl:if test="$d != '' and $m != ''">
    <xsl:value-of select="$d"/>
    <xsl:text> </xsl:text>
        <xsl:choose>
          <xsl:when test="$m = 'Jan'">JANUARY</xsl:when>
          <xsl:when test="$m = 'Feb'">FEBRUARY</xsl:when>
          <xsl:when test="$m = 'Mar'">MARCH</xsl:when>
          <xsl:when test="$m = 'Apr'">APRIL</xsl:when>
          <xsl:when test="$m = 'May'">MAY</xsl:when>
          <xsl:when test="$m = 'Jun'">JUNE</xsl:when>
          <xsl:when test="$m = 'Jul'">JULY</xsl:when>
          <xsl:when test="$m = 'Aug'">AUGUST</xsl:when>
          <xsl:when test="$m = 'Sep'">SEPTEMBER</xsl:when>
          <xsl:when test="$m = 'Oct'">OCTOBER</xsl:when>
          <xsl:when test="$m = 'Nov'">NOVEMBER</xsl:when>
          <xsl:when test="$m = 'Dec'">DECEMBER</xsl:when>
          <xsl:otherwise><xsl:value-of select="$m"/></xsl:otherwise>
        </xsl:choose>
    <xsl:text> </xsl:text>
    <xsl:value-of select="$y"/>
  </xsl:if>
</xsl:template>

<xsl:template match="/">
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <!-- The canonical human route is /insights/subscribe. This endpoint is for
       machines, and it stays out of the index as it always has. -->
  <meta name="robots" content="noindex"/>
  <title><xsl:value-of select="rss/channel/title"/></title>
  <style>
/* ---------------------------------------------------------------------- */
/* THE SITE SHELL, read from insights/subscribe.html by                     */
/* research/gen_feed_xsl.py and emitted unaltered. It stays at document     */
/* level so the menu and the footer read the site's own tokens.             */
/* ---------------------------------------------------------------------- */
/* ------------------------------------------------------------------ */
    /* THE SITE SHELL. Copied unaltered from insights/index.html: the nav,  */
    /* the footer, the reset and the tokens they read. This page adds no    */
    /* menu and no footer of its own - it carries the ones the site already */
    /* owns, which is the only way a static page can be surrounded by them  */
    /* (Lock 01). Nothing here is page-specific and nothing here is edited. */
    /* The site-wide --yellow token keeps its site-wide value.              */
    /* ------------------------------------------------------------------ */
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    :root {
      --paper: #ffffff;
      --ink: #0e0e0e;
      --body: #4b4b4b;
      --muted: #8a8a8a;
      --line: #e7e6e2;
      --yellow: #ffe000;
      --panel: #f7f6f3;
    }
    html { scroll-behavior: smooth; }
    body { background: var(--paper); color: var(--ink); font-family: Arial, Helvetica, sans-serif; font-weight: 400; line-height: 1.6; font-size: 16px; -webkit-font-smoothing: antialiased; }
    img { display: block; max-width: 100%; }
    .inner { max-width: 1240px; margin: 0 auto; }

    /* NAV */
    .site-nav { position: fixed; top: 0; left: 0; right: 0; z-index: 100; display: flex; align-items: center; justify-content: space-between; padding: 16px 48px; background: rgba(255,255,255,0.95); backdrop-filter: blur(8px); border-bottom: 1px solid var(--line); }
    .brand { display: flex; align-items: baseline; gap: 7px; text-decoration: none; }
    .brand img { height: 21px; align-self: center; }
    .brand .lab { font-weight: 600; font-size: 15px; color: var(--ink); letter-spacing: -0.01em; }
    .nav-mid { display: flex; gap: 32px; }
    .nav-mid a { font-size: 12px; letter-spacing: 0.06em; text-transform: uppercase; color: #3a3a3a; text-decoration: none; font-weight: 500; padding-bottom: 3px; transition: color 0.2s; }
    .nav-mid a:hover { color: var(--ink); }
    .nav-mid a.active { border-bottom: 2px solid var(--ink); color: var(--ink); }
    .nav-cta { display: inline-flex; align-items: center; gap: 10px; background: var(--ink); color: #fff; font-size: 11px; font-weight: 600; letter-spacing: 0.08em; text-transform: uppercase; padding: 12px 20px; text-decoration: none; transition: background 0.2s; }
    .nav-cta:hover { background: #000; }
    .nav-toggle { display: none; background: none; border: none; cursor: pointer; padding: 6px; }
    .nav-toggle span { display: block; width: 22px; height: 2px; background: var(--ink); margin: 5px 0; transition: transform 0.3s, opacity 0.3s; }

    /* FOOTER */
    .site-footer { background: #0e0e0e; color: #fff; padding: 72px 48px 36px; }
    .foot-top { display: grid; grid-template-columns: 1.4fr repeat(3, 1fr) 1.2fr; gap: 40px; padding-bottom: 56px; border-bottom: 1px solid #262626; }
    .foot-brand img { height: 22px; filter: invert(1); margin-bottom: 18px; }
    .foot-brand .fb-lab { font-size: 11px; letter-spacing: 0.16em; text-transform: uppercase; color: rgba(255,255,255,0.5); font-weight: 600; margin-bottom: 10px; }
    .foot-brand p { font-size: 14px; color: rgba(255,255,255,0.55); line-height: 1.5; max-width: 220px; }
    .foot-col h4 { font-size: 10px; letter-spacing: 0.16em; text-transform: uppercase; color: rgba(255,255,255,0.4); font-weight: 600; margin-bottom: 18px; }
    .foot-col a { display: block; font-size: 14px; color: rgba(255,255,255,0.72); text-decoration: none; margin-bottom: 11px; transition: color 0.2s; }
    .foot-col a:hover { color: #fff; }
    .foot-contact h4 { font-size: 10px; letter-spacing: 0.16em; text-transform: uppercase; color: rgba(255,255,255,0.4); font-weight: 600; margin-bottom: 18px; }
    .foot-contact a.mail { font-size: 14px; color: #fff; text-decoration: none; display: block; margin-bottom: 10px; }
    .foot-contact .loc { font-size: 14px; color: rgba(255,255,255,0.55); margin-bottom: 18px; }
    .foot-social { display: flex; gap: 14px; }
    .foot-social a { color: rgba(255,255,255,0.6); transition: color 0.2s; }
    .foot-social a:hover { color: #fff; }
    .foot-bottom { display: flex; align-items: center; justify-content: space-between; padding-top: 28px; flex-wrap: wrap; gap: 16px; }
    .foot-bottom .copy { font-size: 12px; color: rgba(255,255,255,0.4); }
    .foot-legal { display: flex; gap: 24px; }
    .foot-legal a { font-size: 12px; letter-spacing: 0.04em; text-transform: uppercase; color: rgba(255,255,255,0.4); text-decoration: none; transition: color 0.2s; }
    .foot-legal a:hover { color: #fff; }

    @media (max-width: 880px) {
      .site-nav { padding: 14px 24px; }
      .nav-mid { display: none; position: absolute; top: 100%; left: 0; right: 0; background: #fff; border-bottom: 1px solid var(--line); flex-direction: column; gap: 0; padding: 12px 24px 20px; }
      .nav-mid.open { display: flex; }
      .nav-mid a { padding: 12px 0; }
      .nav-cta { display: none; }
      .nav-toggle { display: block; }
      .nav-toggle.open span:nth-child(1) { transform: rotate(45deg) translate(5px,5px); }
      .nav-toggle.open span:nth-child(2) { opacity: 0; }
      .nav-toggle.open span:nth-child(3) { transform: rotate(-45deg) translate(5px,-5px); }
      .foot-top { grid-template-columns: 1fr 1fr; gap: 32px; }
      .site-footer { padding: 56px 24px 32px; }
    }
    @media (max-width: 560px) {
      .foot-top { grid-template-columns: 1fr; }
    }

    /* ------------------------------------------------------------------ */
    /* THE APPROVED PAGE. Everything below is the v1.0 package stylesheet,  */
    /* carried across in source order and scoped under .is1 by              */
    /* research/port_approved_css.py. It is a mechanical transform, not a   */
    /* hand-filtered one, and `--write` regenerates it - see the module     */
    /* header for why that matters. The package's own :root becomes .is1,   */
    /* so the #ffe500 signal yellow lives on this page's wrapper and the    */
    /* site-wide --yellow above is untouched (Lock 04).                     */
    /* ------------------------------------------------------------------ */

/* ---------------------------------------------------------------------- */
/* THE APPROVED PACKAGE, every selector scoped under .fv1. See        */
/* scoped_package_css() for why this is load-bearing rather than tidy.      */
/* ---------------------------------------------------------------------- */
.fv1{--yellow: #ffe500;
  --ink: #171717;
  --black: #0e0e0e;
  --muted: #6b6b6b;
  --line: #d5d7d7;
  --soft: #f1f3f3;
  --paper: #ffffff;}
.fv1 *{box-sizing: border-box;}
.fv1{scroll-behavior: smooth;}
.fv1{margin: 0;
  background: var(--paper);
  color: var(--ink);
  font-family: Arial, Helvetica, sans-serif;
  font-size: 16px;
  line-height: 1.55;
  -webkit-font-smoothing: antialiased;}
.fv1 a{color: inherit;}
.fv1 button,.fv1 input{font: inherit;}
.fv1 .shell{width: min(1360px, calc(100% - 80px)); margin: 0 auto;}
.fv1 .button span,.fv1 .text-link span,.fv1 .preview-link span{margin-left: 10px;}
.fv1 .subscribe-hero{padding: 38px 0 76px;}
.fv1 .breadcrumb{display: flex;
  gap: 11px;
  margin: 0 0 32px;
  color: #8a8a8a;
  font-size: 11px;
  font-weight: 700;
  letter-spacing: .15em;}
.fv1 .breadcrumb a{text-decoration: none;}
.fv1 .signal-line{height: 7px; background: var(--yellow);}
.fv1 .hero-grid{display: grid;
  grid-template-columns: minmax(0, 1.7fr) minmax(300px, .7fr);
  gap: 86px;
  padding-top: 62px;}
.fv1 .kicker,.fv1 .control-label,.fv1 .issue-label,.fv1 .entry-meta{margin: 0;
  font-size: 11px;
  font-weight: 700;
  letter-spacing: .16em;}
.fv1 .kicker{color: #777;}
.fv1 .kicker-light{color: #a8a8a8;}
.fv1 .hero-grid h1{max-width: 850px;
  margin: 18px 0 24px;
  font-size: clamp(58px, 6.2vw, 90px);
  font-weight: 400;
  letter-spacing: -.055em;
  line-height: .97;}
.fv1 .hero-copy{max-width: 670px;
  margin: 0;
  color: #5d5d5d;
  font-size: 20px;
  line-height: 1.55;}
.fv1 .hero-aside{align-self: end;
  padding: 30px 0 10px 36px;
  border-left: 1px solid var(--line);}
.fv1 .aside-label{margin: 0 0 18px; color: #777; font-size: 11px; font-weight: 700; letter-spacing: .16em;}
.fv1 .aside-lede{margin: 0 0 24px; font-size: 22px;}
.fv1 .hero-aside ul{margin: 0; padding: 0; list-style: none; color: #666;}
.fv1 .hero-aside li{padding: 8px 0; border-top: 1px solid #e5e5e5;}
.fv1 .feed-action-section{background: var(--black); color: #fff;}
.fv1 .feed-action-grid{min-height: 455px;
  display: grid;
  grid-template-columns: .82fr 1.18fr;}
.fv1 .feed-intro{padding: 76px 70px 70px 0; border-right: 1px solid #383838;}
.fv1 .feed-intro h2{margin: 22px 0 0; font-size: clamp(40px, 4vw, 62px); font-weight: 400; letter-spacing: -.045em; line-height: 1.02;}
.fv1 .feed-control{padding: 76px 0 54px 76px;}
.fv1 .control-label{color: #999;}
.fv1 .feed-url{margin: 18px 0 20px; padding-bottom: 18px; border-bottom: 1px solid #464646; font-size: clamp(22px, 2.3vw, 34px); letter-spacing: -.025em; overflow-wrap: anywhere;}
.fv1 .control-copy{max-width: 670px; margin: 0; color: #b7b7b7;}
.fv1 .control-actions{display: flex; gap: 12px; margin-top: 32px;}
.fv1 .button{min-height: 49px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border: 1px solid transparent;
  border-radius: 0;
  padding: 13px 20px;
  cursor: pointer;
  font-size: 11px;
  font-weight: 700;
  letter-spacing: .08em;
  text-decoration: none;}
.fv1 .button-yellow{background: var(--yellow); color: var(--ink);}
.fv1 .button-light{border-color: #666; background: transparent; color: #fff;}
.fv1 .button:focus-visible,.fv1 a:focus-visible{outline: 3px solid var(--yellow); outline-offset: 4px;}
.fv1 .preview-link{display: inline-block;
  margin-top: 34px;
  color: #aaa;
  font-size: 10px;
  font-weight: 700;
  letter-spacing: .12em;
  text-decoration: none;}
.fv1 .how-section{padding: 96px 0 110px;}
.fv1 .section-heading{display: grid; grid-template-columns: .35fr 1fr; gap: 50px; align-items: start;}
.fv1 .section-heading h2{max-width: 760px; margin: 0; font-size: clamp(38px, 4.3vw, 64px); font-weight: 400; letter-spacing: -.045em; line-height: 1.05;}
.fv1 .steps{display: grid; grid-template-columns: repeat(3, 1fr); margin-top: 72px; border-top: 1px solid var(--line);}
.fv1 .steps article{min-height: 255px; padding: 30px 38px 24px 0; border-right: 1px solid var(--line);}
.fv1 .steps article + article{padding-left: 38px;}
.fv1 .steps article:last-child{border-right: 0;}
.fv1 .step-number{margin: 0 0 42px; color: #8a8a8a; font-size: 11px; letter-spacing: .14em;}
.fv1 .steps h3{margin: 0 0 15px; font-size: 24px; font-weight: 500; letter-spacing: -.025em;}
.fv1 .steps article > p:last-child{margin: 0; color: #666;}
.fv1 .latest-section{border-top: 1px solid var(--line); background: var(--soft);}
.fv1 .latest-grid{display: grid; grid-template-columns: .72fr 1.28fr; gap: 86px; padding-top: 94px; padding-bottom: 100px;}
.fv1 .latest-heading{padding-right: 50px;}
.fv1 .latest-heading h2{margin: 18px 0 24px; font-size: clamp(40px, 4vw, 60px); font-weight: 400; letter-spacing: -.045em; line-height: 1.05;}
.fv1 .latest-heading > p:last-child{color: #666;}
.fv1 .latest-list{border-top: 1px solid #bfc2c2;}
.fv1 .latest-list article{padding: 30px 0 32px; border-bottom: 1px solid #c9cccc;}
.fv1 .issue-label{color: #777;}
.fv1 .latest-list h3{margin: 10px 0 10px; font-size: 27px; font-weight: 500; letter-spacing: -.025em; line-height: 1.15;}
.fv1 .latest-list article > p:last-child{max-width: 760px; margin: 0; color: #666;}
.fv1 .text-link{display: inline-block; margin-top: 30px; font-size: 11px; font-weight: 700; letter-spacing: .1em; text-decoration: none;}
.fv1 .feed-view{min-height: 100vh; background: #fff;}
.fv1 .feed-view-intro{width: min(1240px, calc(100% - 72px)); display: grid; grid-template-columns: .9fr .8fr; gap: 100px; margin: 0 auto; padding: 52px 0 62px; position: relative;}
.fv1 .feed-view-intro .signal-line{position: absolute; top: 0; left: 0; right: 0;}
.fv1 .feed-view-intro h1{margin: 16px 0 0; font-size: clamp(50px, 5.5vw, 76px); font-weight: 400; letter-spacing: -.05em; line-height: 1;}
.fv1 .feed-view-intro > p{align-self: end; margin: 0; padding-left: 34px; border-left: 1px solid var(--line); color: #666; font-size: 17px;}
.fv1 .feed-address-band{display: grid; grid-template-columns: 180px 1fr auto; gap: 32px; align-items: center; padding: 24px max(36px, calc((100vw - 1240px) / 2)); background: var(--black); color: #fff;}
.fv1 .feed-address-band span{color: #999; font-size: 10px; font-weight: 700; letter-spacing: .14em;}
.fv1 .feed-address-band strong{font-size: 18px; font-weight: 400; overflow-wrap: anywhere;}
.fv1 .feed-address-band a{font-size: 10px; font-weight: 700; letter-spacing: .1em; text-decoration: none;}
.fv1 .feed-entries{width: min(1240px, calc(100% - 72px)); margin: 0 auto;}
.fv1 .feed-entries article{display: grid; grid-template-columns: 70px 1fr 40px; gap: 28px; padding: 40px 0 42px; border-bottom: 1px solid var(--line);}
.fv1 .entry-index{margin: 6px 0 0; color: #999; font-size: 11px; letter-spacing: .14em;}
.fv1 .entry-meta{color: #777;}
.fv1 .feed-entries h2{margin: 12px 0 12px; font-size: clamp(28px, 3vw, 42px); font-weight: 400; letter-spacing: -.035em; line-height: 1.08;}
.fv1 .feed-entries article div > p:last-child{max-width: 820px; margin: 0; color: #666;}
.fv1 .entry-arrow{align-self: center; font-size: 27px;}
@media (max-width: 900px){
.fv1 .shell{width: min(100% - 36px, 760px);}
.fv1 .hero-grid,.fv1 .feed-action-grid,.fv1 .latest-grid,.fv1 .section-heading{grid-template-columns: 1fr;}
.fv1 .hero-grid{gap: 46px;}
.fv1 .hero-aside{align-self: auto;}
.fv1 .feed-intro{padding-right: 0; border-right: 0; border-bottom: 1px solid #383838;}
.fv1 .feed-control{padding-left: 0;}
.fv1 .steps{grid-template-columns: 1fr;}
.fv1 .steps article,.fv1 .steps article + article{min-height: 0; padding: 28px 0; border-right: 0; border-bottom: 1px solid var(--line);}
.fv1 .step-number{margin-bottom: 20px;}
.fv1 .feed-view-intro{grid-template-columns: 1fr; gap: 38px;}
.fv1 .feed-view-intro > p{align-self: auto;}
.fv1 .feed-address-band{grid-template-columns: 1fr;}
}
@media (max-width: 560px){
.fv1 .subscribe-hero{padding-top: 26px;}
.fv1 .hero-grid{padding-top: 42px;}
.fv1 .hero-grid h1{font-size: 54px;}
.fv1 .hero-copy{font-size: 17px;}
.fv1 .hero-aside{padding-left: 20px;}
.fv1 .feed-action-grid{min-height: 0;}
.fv1 .feed-intro,.fv1 .feed-control{padding-top: 52px; padding-bottom: 48px;}
.fv1 .control-actions{flex-direction: column; align-items: stretch;}
.fv1 .button{width: 100%;}
.fv1 .how-section{padding: 72px 0;}
.fv1 .latest-grid{gap: 44px; padding-top: 72px;}
.fv1 .feed-view-intro,.fv1 .feed-entries{width: calc(100% - 36px);}
.fv1 .feed-view-intro{padding-top: 44px;}
.fv1 .feed-view-intro > p{padding-left: 20px;}
.fv1 .feed-address-band{padding: 24px 18px;}
.fv1 .feed-entries article{grid-template-columns: 34px 1fr; gap: 16px;}
.fv1 .entry-arrow{display: none;}
}

/* Production deviations, appended after the package stylesheet and never
   folded into it. See the DEVIATIONS note in research/gen_feed_xsl.py. */
.fv1 .feed-entries h2 a{text-decoration:none}
.fv1 .feed-entries .entry-arrow{text-decoration:none}

/* THE SHELL ON THIS PAGE, RATIFIED. GPT, handover v1.1, 23 August 2026:
   Thomas's instruction is approved as a v1.1 override that supersedes
   03-RSS-BROWSER-SPEC.md's "Visual boundary" FOR THE FEED VIEW ONLY. The
   existing yellow3 menu and footer stay, the shell keeps its own tokens, the
   package stays scoped beneath .fv1, signal yellow stays #FFE500, and no
   package token may repaint the menu or the footer. v1.0 is not rewritten -
   the decision record is research/approved/insights-subscribe-v1.1.md.

   THE OPENING, ruled in the same pass: the signal rule must not touch the menu
   border. The feed view now opens with the subscription page's rhythm - 38px
   of clear space under the menu at desktop and tablet, 26px under the mobile
   menu - and the 7px rule follows that space.

   The nav is position:fixed and is 74.6px tall above 880px, 67px below it,
   where its padding drops and the CTA is display:none. The clear space is
   ADDED to the nav height, never substituted for it. Three bands, because the
   nav changes height at 880px and the clear space changes at 560px:

       above 880px    74.6 + 38     desktop
       561 - 880px    67   + 38     tablet, shorter nav, same clear space
       to 560px       67   + 26     mobile

   Cleared on .feed-view and not .feed-view-intro, deliberately: the rule is
   absolutely positioned at the intro's top, so padding the intro would leave
   the rule behind the menu instead of below it. All internal feed-view
   geometry beneath the rule is untouched - the intro keeps its 52px opening,
   so rule to eyebrow stays at 45px. */
.fv1.feed-view{padding-top:calc(74.6px + 38px)}
@media (max-width:880px){.fv1.feed-view{padding-top:calc(67px + 38px)}}
@media (max-width:560px){.fv1.feed-view{padding-top:calc(67px + 26px)}}
  </style>
</head>
<body>

<nav class="site-nav">
    <a href="/" class="brand"><img src="/logo.png" alt="yellow3" /></a>
    <div class="nav-mid" id="navMid">
      <a href="/research">Research</a>
      <a href="/platforms">Platforms</a>
      <a href="/insights/" class="active">Insights</a>
      <a href="/advisory">Advisory</a>
      <a href="/about">About</a>
      <a href="/contact">Contact</a>
    </div>
    <a href="/insights/subscribe" class="nav-cta">Subscribe <span>&#8594;</span></a>
    <button class="nav-toggle" aria-label="Menu" onclick="this.classList.toggle('open');document.getElementById('navMid').classList.toggle('open')"><span></span><span></span><span></span></button>
  </nav>

<main class="feed-view fv1">

  <section class="feed-view-intro">
    <div class="signal-line" aria-hidden="true"></div>
    <div>
      <p class="kicker">RSS 2.0 &#183; YELLOW3 INSIGHTS</p>
      <h1>The publication feed.</h1>
    </div>
    <p>This is a machine-readable RSS feed with a human browser presentation. Copy the address into your feed reader to receive new yellow3 Insights in chronological order.</p>
  </section>

  <section class="feed-address-band">
    <span>FEED ADDRESS</span>
    <strong>https://www.yellow3.io/feed.xml</strong>
    <a href="/insights/subscribe">HOW TO SUBSCRIBE <span>&#8594;</span></a>
  </section>

  <section class="feed-entries" aria-label="Feed entries">
    <xsl:for-each select="rss/channel/item">
      <article>
        <p class="entry-index"><xsl:number format="01" value="position()"/></p>
        <div>
          <xsl:if test="normalize-space(pubDate) != ''">
            <p class="entry-meta">
              <xsl:call-template name="pubdate">
                <xsl:with-param name="raw" select="pubDate"/>
              </xsl:call-template>
            </p>
          </xsl:if>
          <h2>
            <xsl:choose>
              <xsl:when test="normalize-space(link) != ''">
                <a>
                  <xsl:attribute name="href"><xsl:value-of select="link"/></xsl:attribute>
                  <xsl:value-of select="title"/>
                </a>
              </xsl:when>
              <xsl:otherwise><xsl:value-of select="title"/></xsl:otherwise>
            </xsl:choose>
          </h2>
          <xsl:if test="normalize-space(description) != ''">
            <p><xsl:value-of select="description"/></p>
          </xsl:if>
        </div>
        <xsl:if test="normalize-space(link) != ''">
          <a class="entry-arrow" aria-hidden="true">
            <xsl:attribute name="href"><xsl:value-of select="link"/></xsl:attribute>
            <xsl:text>&#8594;</xsl:text>
          </a>
        </xsl:if>
      </article>
    </xsl:for-each>
  </section>

</main>

<footer class="site-footer">
    <div class="inner">
      <div class="foot-top">
        <div class="foot-brand">
          <img src="/logo.png" alt="yellow3" />
          <div class="fb-lab">yellow3 lab</div>
          <p>We use emerging technology to make business less complicated.</p>
        </div>
        <div class="foot-col">
          <h4>Platforms</h4>
          <a href="https://naffe.ai/">naffe.ai</a>
          <a href="/software">Software</a>
          <a href="/platforms">All platforms</a>
        </div>
        <div class="foot-col">
          <h4>Research</h4>
          <a href="/research">Research areas</a>
          <a href="/research/model-adoption">Model adoption</a>
          <a href="/research/eu-ai-act">EU AI Act</a>
          <a href="/research/digital-product-passport/suppliers">DPP Supplier Register</a>
        </div>
        <div class="foot-col">
          <h4>Company</h4>
          <a href="/about">About</a>
          <a href="/advisory">Advisory</a>
          <a href="/insights/">Insights</a>
          <a href="/contact">Contact</a>
        </div>
        <div class="foot-contact">
          <h4>Get in touch</h4>
          <a href="#" onclick="window.location.href=&#39;mailto:&#39;+&#39;hello&#39;+String.fromCharCode(64)+&#39;yellow3.io&#39;;return false;" class="mail">Email us</a>
          <div class="loc">Copenhagen, Denmark</div>
          <div class="foot-social">
            <a href="https://www.linkedin.com/company/yellow3" target="_blank" rel="noopener" aria-label="LinkedIn"><svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor"><path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 1 1 0-4.124 2.062 2.062 0 0 1 0 4.124zM7.119 20.452H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/></svg></a>
            <a href="https://x.com/yellow3HQ" target="_blank" rel="noopener" aria-label="X"><svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/></svg></a>
          </div>
        </div>
      </div>
      <div class="foot-bottom">
        <span class="copy">&#169; 2026 yellow3 ApS. All rights reserved.</span>
        <div class="foot-legal">
          <a href="/privacy">Privacy</a>
          <a href="/terms">Terms</a>
          <a href="/cookies">Cookies</a>
        </div>
      </div>
    </div>
  </footer>

</body>
</html>
</xsl:template>
</xsl:stylesheet>
