#!/usr/bin/env python3
"""
The approved browser presentation for /feed.xml.

WHAT THIS IS. 03-RSS-BROWSER-SPEC.md of the v1.0 handover puts the human layer
ON the feed rather than beside it: /feed.xml stays a valid RSS 2.0 document, and
the presentation is an XSLT stylesheet the browser applies to it. A reader gets
XML. A person gets the approved layout, rendered from the same channel and item
data. There is no second entry list to keep in step, and no production
/feed-preview route - Lock 02 is explicit that the prototype's route was a
design reference only.

WHY IT IS GENERATED. The stylesheet is the approved package stylesheet, carried
in VERBATIM and whole. feed.xsl is a standalone document with no site shell to
collide with, so unlike /insights/subscribe it needs no scoping - but it is
subject to the same lesson research/port_approved_css.py was written for: a
component depends on rules that never mention it, and a stylesheet filtered by
eye loses the ones that look like somebody else's. Nothing here decides which
rules the feed view needs. The package's CSS goes in as it stands.

FAILURE BEHAVIOUR. If this stylesheet fails to load or the browser does not
apply XSLT, the XML is still served and still valid - the presentation is a
layer, never a gate. An item missing an optional field omits that line rather
than showing an invented value.

    python3 research/gen_feed_xsl.py            write feed.xsl
    python3 research/gen_feed_xsl.py --check    fail if feed.xsl is stale
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PACKAGE = os.path.join(ROOT, "research", "approved", "insights-subscribe.approved")
TARGET = os.path.join(ROOT, "feed.xsl")


def package_css():
    html = open(PACKAGE, encoding="utf-8").read()
    m = re.search(r"<style>(.*?)</style>", html, re.S)
    if not m:
        raise SystemExit("no stylesheet block in the approved package")
    css = m.group(1).strip()
    # CSS lives in XML text here. `<` and `&` would end the text node; the
    # package uses neither, and this asserts it rather than assuming it.
    if "<" in css or "&" in css:
        raise SystemExit("package CSS contains < or & - it cannot be inlined "
                         "into XSLT as text without escaping")
    return css


# Approved production deviations, emitted AFTER the package stylesheet and never
# folded into it - the same rule research/port_approved_css.py follows, so the
# port stays a mechanical transform and a deviation stays a decision somebody
# can read.
#
# There is one, and it exists because of a difference between the prototype and
# production that the design intends: 03-RSS-BROWSER-SPEC.md requires "Every row
# links to the canonical article URL from the RSS item", while the prototype's
# feed-preview rows are plain text with no anchors at all. So the package has no
# rule for a link inside an entry, its only anchor rule is a{color:inherit}, and
# every title and arrow renders with the user agent's underline - which is not
# the approved appearance. This restores it. Returned to Thomas and GPT for
# ratification with the v1.0 delivery, 23 August 2026.
DEVIATIONS = """
.feed-entries h2 a{text-decoration:none}
.feed-entries .entry-arrow{text-decoration:none}
"""

# The approved copy, 05-CONTENT-CONTRACT.md, "RSS browser presentation".
EYEBROW = "RSS 2.0 &#183; YELLOW3 INSIGHTS"
HEADLINE = "The publication feed."
EXPLANATION = ("This is a machine-readable RSS feed with a human browser "
               "presentation. Copy the address into your feed reader to receive "
               "new yellow3 Insights in chronological order.")
ADDRESS = "https://www.yellow3.io/feed.xml"

# Month names, spelled out and shouted, the way the approved entry metadata
# reads. XSLT 1.0 has no date parsing, so the RFC-822 pubDate is taken apart by
# delimiter rather than by offset - a single-digit day has no leading zero and
# fixed offsets would silently shift the whole string.
MONTHS = [("Jan", "JANUARY"), ("Feb", "FEBRUARY"), ("Mar", "MARCH"),
          ("Apr", "APRIL"), ("May", "MAY"), ("Jun", "JUNE"),
          ("Jul", "JULY"), ("Aug", "AUGUST"), ("Sep", "SEPTEMBER"),
          ("Oct", "OCTOBER"), ("Nov", "NOVEMBER"), ("Dec", "DECEMBER")]


def month_choose():
    out = ["        <xsl:choose>"]
    for abbr, full in MONTHS:
        out.append('          <xsl:when test="$m = \'%s\'">%s</xsl:when>'
                   % (abbr, full))
    out.append("          <xsl:otherwise><xsl:value-of select=\"$m\"/></xsl:otherwise>")
    out.append("        </xsl:choose>")
    return "\n".join(out)


TEMPLATE = '''<?xml version="1.0" encoding="UTF-8"?>
<!--
  The approved browser presentation for the yellow3 Insights feed, v1.0.

  GENERATED by research/gen_feed_xsl.py. Do not hand-edit: the stylesheet below
  is the approved package stylesheet, verbatim, and a hand edit here is a change
  to an approved design that nothing would catch.

  This file only ever DECORATES /feed.xml. The feed is the canonical, valid RSS
  2.0 document at that address; feed readers never see any of this.
-->
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:atom="http://www.w3.org/2005/Atom"
                xmlns:media="http://search.yahoo.com/mrss/">
<xsl:output method="html" encoding="UTF-8" indent="yes"
            doctype-system="about:legacy-compat"/>

<!-- The publication date, spelled out. An item with no pubDate renders no date
     line at all, rather than an invented one. -->
<xsl:template name="pubdate">
  <xsl:param name="raw"/>
  <xsl:variable name="rest" select="normalize-space(substring-after($raw, ','))"/>
  <xsl:variable name="d" select="substring-before($rest, ' ')"/>
  <xsl:variable name="after" select="substring-after($rest, ' ')"/>
  <xsl:variable name="m" select="substring-before($after, ' ')"/>
  <xsl:variable name="y" select="substring-before(substring-after($after, ' '), ' ')"/>
  <xsl:if test="$d != '' and $m != ''">
    <xsl:value-of select="$d"/>
    <xsl:text> </xsl:text>
{MONTH_CHOOSE}
    <xsl:text> </xsl:text>
    <xsl:value-of select="$y"/>
  </xsl:if>
</xsl:template>

<xsl:template match="/">
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <!-- The canonical human route is /insights/subscribe. This endpoint is for
       machines, and it stays out of the index as it always has. -->
  <meta name="robots" content="noindex"/>
  <title><xsl:value-of select="rss/channel/title"/></title>
  <style>
{CSS}

/* Approved production deviation, appended after the package stylesheet.
   See the DEVIATIONS note in research/gen_feed_xsl.py. */
{DEVIATIONS}
  </style>
</head>
<body>
<main class="feed-view">

  <section class="feed-view-intro">
    <div class="signal-line" aria-hidden="true"></div>
    <div>
      <p class="kicker">{EYEBROW}</p>
      <h1>{HEADLINE}</h1>
    </div>
    <p>{EXPLANATION}</p>
  </section>

  <section class="feed-address-band">
    <span>FEED ADDRESS</span>
    <strong>{ADDRESS}</strong>
    <a href="/insights/subscribe">HOW TO SUBSCRIBE <span>&#8594;</span></a>
  </section>

  <section class="feed-entries" aria-label="Feed entries">
    <xsl:for-each select="rss/channel/item">
      <article>
        <p class="entry-index"><xsl:number format="01" value="position()"/></p>
        <div>
          <xsl:if test="normalize-space(pubDate) != ''">
            <p class="entry-meta">
              <xsl:call-template name="pubdate">
                <xsl:with-param name="raw" select="pubDate"/>
              </xsl:call-template>
            </p>
          </xsl:if>
          <h2>
            <xsl:choose>
              <xsl:when test="normalize-space(link) != ''">
                <a>
                  <xsl:attribute name="href"><xsl:value-of select="link"/></xsl:attribute>
                  <xsl:value-of select="title"/>
                </a>
              </xsl:when>
              <xsl:otherwise><xsl:value-of select="title"/></xsl:otherwise>
            </xsl:choose>
          </h2>
          <xsl:if test="normalize-space(description) != ''">
            <p><xsl:value-of select="description"/></p>
          </xsl:if>
        </div>
        <xsl:if test="normalize-space(link) != ''">
          <a class="entry-arrow" aria-hidden="true">
            <xsl:attribute name="href"><xsl:value-of select="link"/></xsl:attribute>
            <xsl:text>&#8594;</xsl:text>
          </a>
        </xsl:if>
      </article>
    </xsl:for-each>
  </section>

</main>
</body>
</html>
</xsl:template>
</xsl:stylesheet>
'''


def build():
    return (TEMPLATE
            .replace("{MONTH_CHOOSE}", month_choose())
            .replace("{CSS}", package_css())
            .replace("{DEVIATIONS}", DEVIATIONS.strip())
            .replace("{EYEBROW}", EYEBROW)
            .replace("{HEADLINE}", HEADLINE)
            .replace("{EXPLANATION}", EXPLANATION)
            .replace("{ADDRESS}", ADDRESS))


def main():
    fresh = build()
    current = open(TARGET, encoding="utf-8").read() if os.path.exists(TARGET) else None

    if "--check" in sys.argv:
        if current != fresh:
            raise SystemExit("feed.xsl is stale - "
                             "run python3 research/gen_feed_xsl.py")
        print("  ok  feed.xsl: approved presentation, package stylesheet verbatim")
        return 0

    if current != fresh:
        open(TARGET, "w", encoding="utf-8").write(fresh)
        print("feed.xsl written")
    else:
        print("feed.xsl current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
